# Example workflow for Next.js projects
# Save this as .github/workflows/ai-review.yml in your Next.js project

name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run AI Review
        uses: cristiancastro/mik-review-ai@main  # Change to your fork if needed
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          rules_file: '.review-rules.md'
          model_name: 'gpt-4o'
