import * as core from '@actions/core';
import { createAIProvider, AIProviderType } from './ai/factory';
import { GitHubService } from './github/github.service';
import { ConfigLoader } from './config/config.loader';
import * as dotenv from 'dotenv';

// Load env vars for local development if needed
dotenv.config();

async function run() {
    try {
        // 1. Get Inputs
        const openaiApiKey = core.getInput('openai_api_key') || process.env.OPENAI_API_KEY || '';
        const githubToken = core.getInput('github_token') || process.env.GITHUB_TOKEN || '';
        const rulesFilePath = core.getInput('rules_file') || '.review-rules.md';
        let modelName = core.getInput('model_name') || 'gpt-4o';

        core.info(`Provider: OpenAI`);
        core.info(`Model: ${modelName}`);

        if (!githubToken) {
            throw new Error('GitHub Token is required (input: github_token or env: GITHUB_TOKEN)');
        }

        if (!openaiApiKey) {
            throw new Error('OpenAI API Key is required (input: openai_api_key or env: OPENAI_API_KEY)');
        }

        // 2. Initialize Services
        const aiProvider = createAIProvider(openaiApiKey, AIProviderType.OPENAI);
        const githubService = new GitHubService(githubToken);

        // 3. Load Rules/Instructions
        let rulesContent = '';
        try {
            rulesContent = ConfigLoader.loadRules(rulesFilePath);
            core.info(`Loaded review rules from ${rulesFilePath}`);
        } catch (error) {
            core.warning(`Could not load rules file at ${rulesFilePath}. Using default generic instructions.`);
            rulesContent = "Follow best practices for clean, efficient, and secure code.";
        }

        // 4. Fetch PR Diff
        core.info('Fetching PR diff...');
        const diff = await githubService.getPRDiff();
        
        // Basic check to avoid sending empty diffs
        if (!diff || diff.length === 0) {
            core.info('No changes detected in diff. Skipping review.');
            return;
        }

        // 5. Generate Review
        core.info(`Generating review using OpenAI model: ${modelName}...`);
        const reviewResult = await aiProvider.reviewCode({
            diff,
            instructions: rulesContent,
            model: modelName
        });

        // 6. Post Review (Inline Comments + Summary)
        core.info('Posting review to GitHub...');
        const summary = `## 🤖 AI Code Review\n\n${reviewResult.review}\n\n---\n*Generated by mik-review-ai using OpenAI*`;
        
        await githubService.postReview(summary, reviewResult.comments || []);

        core.info('Review completed successfully.');

    } catch (error) {
        if (error instanceof Error) {
            core.setFailed(error.message);
        } else {
            core.setFailed('An unexpected error occurred.');
        }
    }
}

run();