import * as core from '@actions/core';
import { createAIProvider, AIProviderType } from './ai/factory';
import { GitHubService } from './github/github.service';
import { ConfigLoader } from './config/config.loader';
import * as dotenv from 'dotenv';

// Load env vars for local development if needed
dotenv.config();

async function run() {
    try {
        // 1. Get Inputs
        let provider = (core.getInput('provider') || process.env.AI_PROVIDER || 'gemini').toLowerCase();
        const openaiApiKey = core.getInput('openai_api_key') || process.env.OPENAI_API_KEY;
        const geminiApiKey = core.getInput('gemini_api_key') || process.env.GEMINI_API_KEY;
        const githubToken = core.getInput('github_token') || process.env.GITHUB_TOKEN;
        const rulesFilePath = core.getInput('rules_file') || '.review-rules.md';
        let modelName = core.getInput('model_name');

        core.info(`[DEBUG] Raw Inputs - Provider: ${core.getInput('provider')}, Model: ${modelName}`);
        core.info(`[DEBUG] Resolved Provider: ${provider}`);
        
        if (!githubToken) {
            throw new Error('GitHub Token is required (input: github_token or env: GITHUB_TOKEN)');
        }

        // 2. Initialize Services
        const aiProvider = createAIProvider(AIProviderType.OPENAI, openaiApiKey);
        const githubService = new GitHubService(githubToken);

        // 3. Load Rules/Instructions
        let rulesContent = '';
        try {
            rulesContent = ConfigLoader.loadRules(rulesFilePath);
            core.info(`Loaded review rules from ${rulesFilePath}`);
        } catch (error) {
            core.warning(`Could not load rules file at ${rulesFilePath}. Using default generic instructions.`);
            rulesContent = "Follow best practices for clean, efficient, and secure code.";
        }

        // 4. Fetch PR Diff
        core.info('Fetching PR diff...');
        const diff = await githubService.getPRDiff();
        
        // Basic check to avoid sending empty diffs or massive ones (can be improved later)
        if (!diff || diff.length === 0) {
            core.info('No changes detected in diff. Skipping review.');
            return;
        }

        // 5. Generate Review
        core.info(`Generating review using ${modelName}...`);
        const reviewResult = await aiProvider.reviewCode({
            diff,
            instructions: rulesContent,
            model: modelName
        });

        // 6. Post Comment
        core.info('Posting review comment to GitHub...');
        const commentBody = `## 🤖 AI Code Review\n\n${reviewResult.review}\n\n---\n*Generated by mik-review-ai*`;
        await githubService.postComment(commentBody);

        core.info('Review completed successfully.');

    } catch (error) {
        if (error instanceof Error) {
            core.setFailed(error.message);
        } else {
            core.setFailed('An unexpected error occurred.');
        }
    }
}

run();
